# Generated by Django 5.1.2 on 2024-10-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='place',
            new_name='contry',
        ),
        migrations.AddField(
            model_name='info',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='house',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
