# Generated by Django 5.1.2 on 2024-10-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_place_info_contry_info_city_info_house_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='worketime',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
