# Generated by Django 5.1.2 on 2024-10-20 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_specialization_profile_specialization'),
        ('job', '0017_alter_job_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='job.category'),
            preserve_default=False,
        ),
    ]
