# Generated by Django 5.1.2 on 2024-10-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField()),
                ('cv', models.FileField(upload_to=None)),
                ('cover_letter', models.TextField(max_length=1500)),
            ],
        ),
    ]
